export const projects = [
  {
    title: 'Movieland',
    description: "Built a basic website to search for movies using OmbB API and ReactJs.",
      image: '/images/movieland.png',
      tags: ['React', 'RestAPI'],
    source: 'https://github.com/skynette/movieland-react-basics',
    visit: 'https://movieland-react-basics.netlify.app/',
    id: 0,
  },
  {
    title: 'Movieland',
    description: "Using React.",
      image: '/images/movieland.png',
      tags: ['React', "Python", "Django"],
    source: 'https://github.com/skynette/movieland-react-basics',
    visit: 'hhttps://movieland-react-basics.netlify.app/',
    id: 1,
  },
  {
    title: 'Movieland',
    description: "Using React.",
      image: '/images/movieland.png',
      tags: ['React', "Django rest framework"],
    source: 'https://github.com/skynette/movieland-react-basics',
    visit: 'https://movieland-react-basics.netlify.app/',
    id: 2,
  },
  {
    title: 'Movieland',
    description: "Using React.",
      image: '/images/movieland.png',
      tags: ['React'],
    source: 'https://github.com/skynette/movieland-react-basics',
    visit: 'https://movieland-react-basics.netlify.app/',
    id: 3,
  },
  {
    title: 'Movieland',
    description: "Using React.",
      image: '/images/movieland.png',
      tags: ['React'],
    source: 'https://github.com/skynette/movieland-react-basics',
    visit: 'https://movieland-react-basics.netlify.app/',
    id: 4,
  },
];

export const TimeLineData = [
  { year: 2017, text: 'Started my journey', },
  { year: 2018, text: 'Worked as a freelance developer', },
  { year: 2019, text: 'Founded San Tech', },
  { year: 2020, text: 'Shared my projects with the world', },
  { year: 2021, text: 'Started my own platform', },
];