export const projects = [
	{
		title: 'uTube',
		description: "uTube is a web application built with React and Material UI that allows users to search and watch YouTube videos.",
		image: '/images/uTube.png',
		tags: ['React', 'MUIv5','RestAPI'],
		source: 'https://github.com/skynette/uTube',
		visit: 'https://utube-v01.netlify.app/',
		id: 3,
		inDevelopment: false,
	},
	{
		title: 'Photo ALbum',
		description: "",
		image: '/images/photo_album.png',
		tags: ['React', 'Redux/Toolkit', 'MUIv5'],
		source: 'https://github.com/skynette/photo-album-template',
		visit: 'https://photo-album-template.vercel.app/',
		id: 2,
		inDevelopment: false,
	},
	{
		title: 'Guuuuuuugle',
		description: "Built a Google search engine clone using an external API and ReactJs.",
		image: '/images/guugle.png',
		tags: ['React', 'RestAPI', 'Tailwind'],
		source: 'https://github.com/skynette/guugle',
		visit: 'https://guuuuuuugle.netlify.app/search',
		id: 2,
		inDevelopment: true,
	},
	{
		title: 'Sociomedia',
		description: "SocialMedia is a social networking web application built with React, Material UI, Node.js, Express, and MongoDB. It allows users to create profiles, make posts, follow other users and like posts.",
		image: '/images/sociomedia.png',
		tags: ['React', 'MUIv5', 'Node', 'Express', 'MongoDB'],
		source: 'https://github.com/skynette/socialmedia',
		visit: 'https://socialmedia-vert.vercel.app/',
		id: 22,
		inDevelopment: false,
	},
	{
		title: 'Movieland',
		description: "Built a basic website to search for movies using OmbB API and ReactJs.",
		image: '/images/movieland.png',
		tags: ['React', 'RestAPI'],
		source: 'https://github.com/skynette/movieland-react-basics',
		visit: 'https://movieland-react-basics.netlify.app/',
		id: 1,
		inDevelopment: false,
	},
];

export const TimeLineData = [
	{ year: 2017, text: 'Started my programming journey as a hobby', },
	{ year: 2019, text: 'Started Working as a freelance developer', },
	{ year: 2019, text: 'Founded San Tech', },
	{ year: 2020, text: 'Shared my projects with the world', },
	{ year: 2021, text: 'Started my own platform', },
];