export const projects = [
  {
    title: 'Movieland',
    description: "Using React.",
      image: '/images/1.png',
      tags: ['React'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 0,
  },
  {
    title: 'Movieland',
    description: "Using React.",
      image: '/images/1.png',
      tags: ['React', "Python", "Django"],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 1,
  },
  {
    title: 'Movieland',
    description: "Using React.",
      image: '/images/1.png',
      tags: ['React', "Django rest framework"],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 2,
  },
  {
    title: 'Movieland',
    description: "Using React.",
      image: '/images/1.png',
      tags: ['React'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 3,
  },
  {
    title: 'Movieland',
    description: "Using React.",
      image: '/images/1.png',
      tags: ['React'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 4,
  },
];

export const TimeLineData = [
  { year: 2017, text: 'Started my journey', },
  { year: 2018, text: 'Worked as a freelance developer', },
  { year: 2019, text: 'Founded San Tech', },
  { year: 2020, text: 'Shared my projects with the world', },
  { year: 2021, text: 'Started my own platform', },
];